### PR TITLE
Change destination dir of build artifacts

### PR DESCRIPTION
**Pull request by yuntan**
Change destination dir of *.js and *.js.map built by tsc to /build, because it is confusing that .js is created in /src.

### CODE REVIEW

**Comment by rhysd** [comment]
Could you describe why it is confusing? It is explicit by its file extension.

**Comment by rhysd** [comment]
I tried this branch on macOS 10.12.

tmp

It seems that font size is wrong while inputing with IME (before input is determined, font size is bigger).

Can you fix this? Or should I try to fix this in my side?

**Comment by yuntan** [comment]
There are two reasons. First, when I open a file from Vim's cmd-line, I'm frustrated to choose correct file, because there are three suggestions.

[https://gyazo.com/4f862892fb3f24cd818ec3d5d401e9af](https://gyazo.com/4f862892fb3f24cd818ec3d5d401e9af)

Second, I think that separating sources and artifacts is the general view of software compilation process.

If you don't get frustrated to open .ts file and don't agree with the second reason, feel free to ignore this pr and close.

**Comment by rhysd** [comment]
ok, I understood that it's frustrating rather than confusing. I don't have a strong opinion for this so I'd select your choice.

**Comment by rhysd** [comment]
Travis CI fails. Tests seem broken.

> Error: Cannot find module '../../src/neovim/store'

I think the failure caused because the import paths from test code to library code are wrong. Could you fix them?

**Comment by yuntan** [comment]
Thank you. It's sorry that my choice of word was wrong. 

I simply rewrote `require('../../src/neovim/...')` to `require('../../build/src/neovim/...')`.

**Comment by rhysd** [comment]
np. Thank you for this.

**Pull request merged**
